Add executable option

diff --git a/my-delcr b/my-delcr
--- a/my-delcr
+++ b/my-delcr
@@ -1,11 +1,41 @@
 #!/bin/sh
 
+# get abs path
 path=`pwd`'/'
-for filename in $@
+FLG_X="FALSE"
+
+# read option
+while getopts xh OPT
 do
-    echo ${path}${filename}
-    tr -d '\r' < ${path}${filename} > ${path}'new_'${filename}
-    rm ${path}${filename}
-    mv ${path}'new_'${filename} ${path}${filename}
-    chmod +x ${path}${filename}
+    case $OPT in
+        "x" ) FLG_X="TRUE" ;;
+        "h" ) echo "my-delcr [-x : change to executable] FILENAMES" 1>&2
+              exit 1 ;;
+          * ) echo "Usage my-delcr [-x] FILENAMES" 1>&2
+              exit 1 ;;
+    esac
+done
+
+# delete option params
+shift `expr $OPTIND - 1`
+
+# convert file
+for filename in "$@"
+do
+    if [ ! -e ${path}${filename} ]; then
+        echo "not found: ${path}${filename}"
+        break
+    fi
+
+    {
+        tr -d '\r' < ${path}${filename} > ${path}'new_'${filename}
+        rm ${path}${filename}
+        mv ${path}'new_'${filename} ${path}${filename}
+        echo ${path}${filename}
+    }
+
+    if [ ${FLG_X} = "TRUE" ]; then
+        echo 'changed to executable'
+        chmod +x ${path}${filename}
+    fi
 done
